# Версия бета-1.0-beta

#########################[Скупщик]#######################

logger: false

priseItem:
  path: priseItem.yml

menu:
  seller:
    path: Menu/seller.yml

  mobs:
    path: Menu/mobs.yml
  mine:
    path: Menu/mine.yml


autoBuyDelay: 60 # В тиках. Как часто будет срабатывать АвтоСкупка. По умолчанию 60 - 3 секунды
autoBuy:
  enable: "&aВключён"
  disable: "&cВыключен"
#########################[Сообщения]#######################
completeSaleMessage: 'Вы успешно продали все предметы на сумму %sum%'
noItemsToSellMessage: 'У вас нет предметов для продажи'
